import { Province, City, BusinessCategory, Business } from '../types';

export const INITIAL_PROVINCES: Province[] = [
  { id: 1, name: 'Buenos Aires', code: 'BA' },
  { id: 2, name: 'Ciudad Autónoma de Buenos Aires', code: 'CABA' },
  { id: 3, name: 'Catamarca', code: 'CAT' },
  { id: 4, name: 'Chaco', code: 'CHA' },
  { id: 5, name: 'Chubut', code: 'CHU' },
  { id: 6, name: 'Córdoba', code: 'CBA' },
  { id: 7, name: 'Corrientes', code: 'COR' },
  { id: 8, name: 'Entre Ríos', code: 'ER' },
  { id: 9, name: 'Formosa', code: 'FOR' },
  { id: 10, name: 'Jujuy', code: 'JUJ' },
  { id: 11, name: 'La Pampa', code: 'LP' },
  { id: 12, name: 'La Rioja', code: 'LR' },
  { id: 13, name: 'Mendoza', code: 'MDZ' },
  { id: 14, name: 'Misiones', code: 'MIS' },
  { id: 15, name: 'Neuquén', code: 'NEU' },
  { id: 16, name: 'Río Negro', code: 'RN' },
  { id: 17, name: 'Salta', code: 'SAL' },
  { id: 18, name: 'San Juan', code: 'SJ' },
  { id: 19, name: 'San Luis', code: 'SL' },
  { id: 20, name: 'Santa Cruz', code: 'SC' },
  { id: 21, name: 'Santa Fe', code: 'SF' },
  { id: 22, name: 'Santiago del Estero', code: 'SDE' },
  { id: 23, name: 'Tierra del Fuego', code: 'TDF' },
  { id: 24, name: 'Tucumán', code: 'TUC' },
];

export const INITIAL_CATEGORIES: BusinessCategory[] = [
  { id: 1, name: 'Mueblería' },
  { id: 2, name: 'Veterinaria' },
  { id: 3, name: 'Dietética' },
  { id: 4, name: 'Ferretería' },
  { id: 5, name: 'Gastronomía' },
  { id: 6, name: 'Gimnasio' },
  { id: 7, name: 'Peluquería' },
  { id: 8, name: 'Hotel' },
  { id: 9, name: 'Estudio contable' },
  { id: 10, name: 'Estudio jurídico' },
  { id: 11, name: 'Tecnología' },
  { id: 12, name: 'Taller mecánico' },
  { id: 13, name: 'Indumentaria' },
  { id: 14, name: 'Inmobiliaria' },
];

export const INITIAL_CITIES: City[] = [
  // Santa Fe (id: 21)
  { id: 1, province_id: 21, name: 'Rosario', population: 1029000, province_name: 'Santa Fe' },
  { id: 2, province_id: 21, name: 'Santa Fe', population: 415000, province_name: 'Santa Fe' },
  { id: 3, province_id: 21, name: 'Rafaela', population: 109000, province_name: 'Santa Fe' },
  { id: 4, province_id: 21, name: 'Cañada de Gómez', population: 30000, province_name: 'Santa Fe' },
  { id: 5, province_id: 21, name: 'Villa Eloísa', population: 3500, province_name: 'Santa Fe' },
  { id: 6, province_id: 21, name: 'Venado Tuerto', population: 82000, province_name: 'Santa Fe' },
  { id: 7, province_id: 21, name: 'Reconquista', population: 78000, province_name: 'Santa Fe' },
  { id: 8, province_id: 21, name: 'Santo Tomé', population: 66000, province_name: 'Santa Fe' },
  { id: 9, province_id: 21, name: 'Esperanza', population: 43000, province_name: 'Santa Fe' },
  { id: 10, province_id: 21, name: 'San Lorenzo', population: 50000, province_name: 'Santa Fe' },

  // Córdoba (id: 6)
  { id: 11, province_id: 6, name: 'Córdoba', population: 1500000, province_name: 'Córdoba' },
  { id: 12, province_id: 6, name: 'Río Cuarto', population: 180000, province_name: 'Córdoba' },
  { id: 13, province_id: 6, name: 'Villa María', population: 90000, province_name: 'Córdoba' },
  { id: 14, province_id: 6, name: 'Villa Carlos Paz', population: 75000, province_name: 'Córdoba' },
  { id: 15, province_id: 6, name: 'San Francisco', population: 65000, province_name: 'Córdoba' },
  { id: 16, province_id: 6, name: 'Bell Ville', population: 38000, province_name: 'Córdoba' },

  // Buenos Aires (id: 1)
  { id: 17, province_id: 1, name: 'La Plata', population: 772000, province_name: 'Buenos Aires' },
  { id: 18, province_id: 1, name: 'Mar del Plata', population: 682000, province_name: 'Buenos Aires' },
  { id: 19, province_id: 1, name: 'Bahía Blanca', population: 335000, province_name: 'Buenos Aires' },
  { id: 20, province_id: 1, name: 'Tandil', population: 150000, province_name: 'Buenos Aires' },
  { id: 21, province_id: 1, name: 'San Nicolás', population: 145000, province_name: 'Buenos Aires' },
  { id: 22, province_id: 1, name: 'Pergamino', population: 105000, province_name: 'Buenos Aires' },
  { id: 23, province_id: 1, name: 'Junín', population: 95000, province_name: 'Buenos Aires' },

  // Mendoza (id: 13)
  { id: 24, province_id: 13, name: 'Mendoza', population: 120000, province_name: 'Mendoza' },
  { id: 25, province_id: 13, name: 'San Rafael', population: 130000, province_name: 'Mendoza' },
  { id: 26, province_id: 13, name: 'Godoy Cruz', population: 195000, province_name: 'Mendoza' },
  { id: 27, province_id: 13, name: 'Guaymallén', population: 320000, province_name: 'Mendoza' },

  // Entre Ríos (id: 8)
  { id: 28, province_id: 8, name: 'Paraná', population: 290000, province_name: 'Entre Ríos' },
  { id: 29, province_id: 8, name: 'Concordia', population: 160000, province_name: 'Entre Ríos' },
  { id: 30, province_id: 8, name: 'Gualeguaychú', population: 95000, province_name: 'Entre Ríos' },
];

export const INITIAL_BUSINESSES: Business[] = [
  {
    id: 1,
    city_id: 1, // Rosario
    category_id: 1, // Mueblería
    name: 'Muebles López',
    address: 'Av. Pellegrini 1420, Rosario',
    phone: '+54 341 4578932',
    whatsapp: '+54 9 341 6213345',
    email: 'contacto@muebleslopez.com.ar',
    instagram: '@muebleslopez.rosario',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=1001',
    source: 'google_maps',
    external_id: 'ChIJ_muebles_lopez_rosario',
    source_url: 'https://maps.google.com/?cid=1001',
    score: 88,
    generated_message: 'Hola, estuve viendo su negocio Muebles López y noté que actualmente no cuentan con un sitio web con catálogo online. Trabajo desarrollando soluciones digitales para fábricas de muebles y creo que podríamos ayudarlos a captar más clientes en Rosario. Si les interesa, puedo mostrarles ejemplos específicos sin compromiso.',
    status: 'NEW',
    notes: 'Excelente local sobre Pellegrini. Tienen mucho stock de algarrobo y pino.',
    created_at: '2026-03-12T14:30:00Z',
    updated_at: '2026-03-12T14:30:00Z',
    city_name: 'Rosario',
    province_name: 'Santa Fe',
    category_name: 'Mueblería',
  },
  {
    id: 2,
    city_id: 1, // Rosario
    category_id: 2, // Veterinaria
    name: 'Veterinaria San Martín',
    address: 'San Martín 3250, Rosario',
    phone: '+54 341 4821199',
    whatsapp: '+54 9 341 5558912',
    email: 'vetsanmartin@gmail.com',
    instagram: '@vet_sanmartin',
    website: 'https://veterinariasanmartin.com.ar',
    has_website: true,
    google_maps_url: 'https://maps.google.com/?cid=1002',
    source: 'google_maps',
    external_id: 'ChIJ_vet_sanmartin_rosario',
    source_url: 'https://maps.google.com/?cid=1002',
    score: 65,
    generated_message: 'Hola, estuve viendo la web de Veterinaria San Martín. Noté que no está adaptada para solicitar turnos online ni urgencias por WhatsApp de forma directa. Desarrollamos herramientas para centros veterinarios para automatizar recordatorios de vacunas. ¿Les gustaría que les comparta una demo?',
    status: 'CONTACTED',
    notes: 'Contactado por WhatsApp el 15/10. Quedó en responder el encargado del turno tarde.',
    created_at: '2026-03-12T11:20:00Z',
    updated_at: '2026-03-12T16:00:00Z',
    city_name: 'Rosario',
    province_name: 'Santa Fe',
    category_name: 'Veterinaria',
  },
  {
    id: 3,
    city_id: 1, // Rosario
    category_id: 3, // Dietética
    name: 'Dietética Madre Tierra',
    address: 'Córdoba 1820, Rosario',
    phone: '+54 341 4247890',
    whatsapp: '+54 9 341 7123984',
    email: 'madretierra.ros@gmail.com',
    instagram: '@madretierra.diet',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=1003',
    source: 'google_maps',
    external_id: 'ChIJ_dietetica_madretierra_rosario',
    source_url: 'https://maps.google.com/?cid=1003',
    score: 92,
    generated_message: 'Hola equipo de Dietética Madre Tierra, vi su local en calle Córdoba y tienen una variedad increíble de productos. Noté que no disponen de menú o tienda web para pedidos por WhatsApp. Desarrollamos catálogos digitales rápidos pensados justo para dietéticas y almacenes naturales. ¿Tienen 5 minutos para coordinar una llamada?',
    status: 'INTERESTED',
    notes: 'Respondieron interesados en armar catálogo para pedidos de oficina en el centro.',
    created_at: '2026-03-11T18:10:00Z',
    updated_at: '2026-03-12T09:40:00Z',
    city_name: 'Rosario',
    province_name: 'Santa Fe',
    category_name: 'Dietética',
  },
  {
    id: 4,
    city_id: 1, // Rosario
    category_id: 4, // Ferretería
    name: 'Ferretería Industrial La Tuerca',
    address: 'Ovidio Lagos 2810, Rosario',
    phone: '+54 341 4339900',
    whatsapp: '+54 9 341 4982103',
    email: 'latuerca.rosario@hotmail.com',
    instagram: '@latuerca_ferreteria',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=1004',
    source: 'google_maps',
    external_id: 'ChIJ_ferreteria_latuerca_rosario',
    source_url: 'https://maps.google.com/?cid=1004',
    score: 78,
    generated_message: 'Hola gente de La Tuerca! Notamos que reciben muchas consultas en su local pero no tienen ficha web con cotizador rápido para talleres y empresas de la zona. ¿Les interesaría ver una solución sencilla?',
    status: 'NEW',
    notes: 'Zona muy comercial en Ovidio Lagos.',
    created_at: '2026-03-10T10:05:00Z',
    updated_at: '2026-03-10T10:05:00Z',
    city_name: 'Rosario',
    province_name: 'Santa Fe',
    category_name: 'Ferretería',
  },
  {
    id: 5,
    city_id: 11, // Córdoba
    category_id: 6, // Gimnasio
    name: 'Gimnasio Titán Fitness',
    address: 'Av. Colón 1250, Córdoba',
    phone: '+54 351 4712390',
    whatsapp: '+54 9 351 6890214',
    email: 'contacto@titanfitnesscba.com',
    instagram: '@titan_fitness_cba',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=2001',
    source: 'google_maps',
    external_id: 'ChIJ_titan_fitness_cordoba',
    source_url: 'https://maps.google.com/?cid=2001',
    score: 85,
    generated_message: 'Hola equipo de Titán Fitness! Estuve viendo sus instalaciones en Av. Colón. Noté que no tienen página web para inscripción de socios ni venta de pases online. Ayudamos a gimnasios a sumar socios con páginas optimizadas para celulares. ¿Les gustaría ver ejemplos?',
    status: 'NEW',
    notes: 'Poco manejo digital en redes pero tienen 400+ reseñas en Google Maps.',
    created_at: '2026-03-09T15:20:00Z',
    updated_at: '2026-03-09T15:20:00Z',
    city_name: 'Córdoba',
    province_name: 'Córdoba',
    category_name: 'Gimnasio',
  },
  {
    id: 6,
    city_id: 11, // Córdoba
    category_id: 1, // Mueblería
    name: 'Mueblería Nueva Era',
    address: 'Humberto 1º 450, Córdoba',
    phone: '+54 351 4220199',
    whatsapp: '+54 9 351 5304921',
    email: 'info@nuevaeramuebles.com.ar',
    instagram: '@nuevaeramuebles',
    website: 'https://nuevaeramuebles.com.ar',
    has_website: true,
    google_maps_url: 'https://maps.google.com/?cid=2002',
    source: 'google_maps',
    external_id: 'ChIJ_muebles_nuevaera_cordoba',
    source_url: 'https://maps.google.com/?cid=2002',
    score: 40,
    generated_message: 'Hola! Vimos su sitio web y notamos que tiene tiempos de carga lentos desde celulares. Podemos colaborar en optimizarlo.',
    status: 'REJECTED',
    notes: 'Tienen agencia propia y no les interesa cambiar por ahora.',
    created_at: '2026-03-08T12:00:00Z',
    updated_at: '2026-03-09T10:15:00Z',
    city_name: 'Córdoba',
    province_name: 'Córdoba',
    category_name: 'Mueblería',
  },
  {
    id: 7,
    city_id: 2, // Santa Fe
    category_id: 9, // Estudio contable
    name: 'Estudio Contable Albarracín & Asoc.',
    address: 'San Jerónimo 2140, Santa Fe',
    phone: '+54 342 4591020',
    whatsapp: '+54 9 342 6112233',
    email: 'consultas@estudioalbarracin.com',
    instagram: '@albarracin_contable',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=3001',
    source: 'google_maps',
    external_id: 'ChIJ_estudio_albarracin_sf',
    source_url: 'https://maps.google.com/?cid=3001',
    score: 90,
    generated_message: 'Estimados Cr. Albarracín: Estuve analizando la presencia digital de estudios contables en Santa Fe y noté que su firma no cuenta con una landing page institucional para captación de pymes y clientes corporativos. Trabajamos exclusivamente en sitios serios y profesionales para profesionales de ciencias económicas. ¿Podríamos coordinar una breve reunión virtual?',
    status: 'CLIENT',
    notes: 'Cerraron el desarrollo de su web institucional y portal de clientes el mes pasado.',
    created_at: '2026-03-05T09:30:00Z',
    updated_at: '2026-03-10T14:20:00Z',
    city_name: 'Santa Fe',
    province_name: 'Santa Fe',
    category_name: 'Estudio contable',
  },
  {
    id: 8,
    city_id: 3, // Rafaela
    category_id: 8, // Hotel
    name: 'Hotel Central Rafaela',
    address: 'Bv. Santa Fe 340, Rafaela',
    phone: '+54 3492 422001',
    whatsapp: '+54 9 3492 511029',
    email: 'reservas@hotelcentralrafaela.com.ar',
    instagram: '@hotelcentralrafaela',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=4001',
    source: 'google_maps',
    external_id: 'ChIJ_hotel_central_rafaela',
    source_url: 'https://maps.google.com/?cid=4001',
    score: 95,
    generated_message: 'Hola! Vimos que reciben muchos viajeros corporativos en Rafaela pero no cuentan con motor de reservas directas en su propia web para evitar comisiones de Booking. ¿Les gustaría ver una alternativa ágil?',
    status: 'NEW',
    notes: 'Muy buena ubicación céntrica. Ideal para ofrecer motor de reservas.',
    created_at: '2026-03-11T16:45:00Z',
    updated_at: '2026-03-11T16:45:00Z',
    city_name: 'Rafaela',
    province_name: 'Santa Fe',
    category_name: 'Hotel',
  },
  {
    id: 9,
    city_id: 4, // Cañada de Gómez
    category_id: 1, // Mueblería
    name: 'Fábrica de Amoblamientos Cañada',
    address: 'Ruta 9 Km 370, Cañada de Gómez',
    phone: '+54 3471 422500',
    whatsapp: '+54 9 3471 654321',
    email: 'ventas@amoblamientoscanada.com.ar',
    instagram: '@amoblamientos_canada',
    website: null,
    has_website: false,
    google_maps_url: 'https://maps.google.com/?cid=5001',
    source: 'google_maps',
    external_id: 'ChIJ_amoblamientos_canada',
    source_url: 'https://maps.google.com/?cid=5001',
    score: 87,
    generated_message: 'Hola! Vimos que son uno de los principales fabricantes de muebles de Cañada de Gómez. Actualmente no tienen catálogo web disponible para distribuidores mayoristas de Santa Fe y Córdoba. Desarrollamos portales B2B rápidos. ¿Les gustaría conocer más detalles?',
    status: 'NEW',
    notes: 'Fabricantes directos, gran potencial para B2B.',
    created_at: '2026-03-10T14:15:00Z',
    updated_at: '2026-03-10T14:15:00Z',
    city_name: 'Cañada de Gómez',
    province_name: 'Santa Fe',
    category_name: 'Mueblería',
  }
];
